### ISSUE TITLE
Problems with running LRTK

### ISSUE THREAD

**Issue by luozhenyu0911** [ericcombiolab/LRTK#1]
Q: I used the exsample data you provided. When I successfully completed the data alignment and processing the BAM file, it stopped in the following steps, do you have any good solutions?

$/home/zhenyuluo/anaconda3/envs/lrtk_p/lib/python3.10/site-packages/script/long_fragment/construct_fragment -d 200000 -t 4 --bam ./Example.bam --output /research/rv-02/home/zhenyuluo/04_lrtk/data2/./constructedfragment.xls > /research/rv-02/home/zhenyuluo/04_lrtk/data2/./constructedfragment.stat.xls
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Aborted

**Comment by CicyYeung** [comment]
Hi, Zhenyu,
     This error happens when trying to reconstruct the fragments with too small linked reads. We tried the reconstruction with at least 1 GB FASTQ files. In our Google Drive, we have included a small data set (FQs) and a large data set (LargeFQs). The LargeFQs could be used to evaluate the reconstruction, while the small data sets are designed for quick tests of acquiring FASTQ files and alignment files. When constructing fragments with small data sets, this error reports. 

Best Regards!
CHAO YANG

**Comment by luozhenyu0911** [comment]
> Hi, Zhenyu, This error happens when trying to reconstruct the fragments with too small linked reads. We tried the reconstruction with at least 1 GB FASTQ files. In our Google Drive, we have included a small data set (FQs) and a large data set (LargeFQs). The LargeFQs could be used to evaluate the reconstruction, while the small data sets are designed for quick tests of acquiring FASTQ files and alignment files. When constructing fragments with small data sets, this error reports.
> 
> Best Regards! CHAO YANG

**Comment by luozhenyu0911** [comment]
> Hi, Zhenyu, This error happens when trying to reconstruct the fragments with too small linked reads. We tried the reconstruction with at least 1 GB FASTQ files. In our Google Drive, we have included a small data set (FQs) and a large data set (LargeFQs). The LargeFQs could be used to evaluate the reconstruction, while the small data sets are designed for quick tests of acquiring FASTQ files and alignment files. When constructing fragments with small data sets, this error reports.
> 
> Best Regards! CHAO YANG

Hi, Chao,

This error also happens with the LargeFQs. I have sent you the specific questions by email.

Best Regards!
Zhenyu.
