### ISSUE TITLE
example function 7 fails looking for missing file header38

### ISSUE THREAD

**Issue by btm685** [ericcombiolab/LRTK#3]
Attempted to run function 7:
$LRTK WGS -SI $Sinfo -OD $OUTDIR -DB $DATABASE -RG "@RG\tID:Example\tSM:Example" -T 32

After a number of hours, it eventually fails like this:
python /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/Reformat.py -r ./database/GRCH38/genome.fa -i /home/bmatthews/lrtk-work/./WGS//Example_10x/SV/tmp.vcf -o /home/bmatthews/lrtk-work/./WGS//Example_10x/SV/Example_10x.largevariants.vcf --add_header 38 --base_norm --gz_tbi^M
Vcf reformat start^M
Traceback (most recent call last):^M
  File "/home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/Reformat.py", line 97, in <module>^M
    modify(vcf_file,genome,vcfwrite,add_chr,add_header,pos_base)^M
  File "/home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/Reformat.py", line 45, in modify^M
    with open(code_path+"header/header"+add_header,"r") as fh:^M
FileNotFoundError: [Errno 2] No such file or directory: '/home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/header/header38'^M
[2022-09-06 17:21:54.357029] report starts: python /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script//report.py -f /home/bmatthews/lrtk-work/./WGS//Example_10x/FQ/FASTQ.QC.json -b /home/bmatthews/lrtk-work/./WGS//Example_10x/QC/Fragment.json -m /home/bmatthews/lrtk-work/./WGS//Example_10x/QC/VCF.json -o /home/bmatthews/lrtk-work/./WGS//Example_10x/Report/Example_10x.report.html^M
[2022-09-06 17:21:54.593876] report fails: python /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script//report.py -f /home/bmatthews/lrtk-work/./WGS//Example_10x/FQ/FASTQ.QC.json -b /home/bmatthews/lrtk-work/./WGS//Example_10x/QC/Fragment.json -m /home/bmatthews/lrtk-work/./WGS//Example_10x/QC/VCF.json -o /home/bmatthews/lrtk-work/./WGS//Example_10x/Report/Example_10x.report.html^M
$ $ echo $?^M
1^M

Additionally, there were 2 core files created along the way, one for cmd 'ema' with no message logged, and one for cmd 'construct_fragment', with this error:

terminate called after throwing an instance of 'std::out_of_range'^M
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)^M
Aborted (core dumped)^M

see attached file 'typescript.txt' for all the output details.  In addition, this file shows my environment vars as well as contents of 'sample.info' and an environment file 'sourceme'.  It is running inside an ubuntu 22.04 Docker container.  Inside that is a conda virtualenv named 'myenv', which is where all the extra python modules for LRTK were installed.

[typescript.txt](https://github.com/ericcombiolab/LRTK/files/9516343/typescript.txt)

**Comment by CicyYeung** [comment]
Thanks for the comments. 
In the log files, the first problem is about errors in running some C++ programs, such as EMA and fragment_construction. Based on the wall clock time to process alignment files (most of them were less than 1 minute), I think, lrtk may fail to generate the alignment files (tmp.ema.bam and tmp.bwa.bam). This also led to failures in following long fragment reconstruction and statistics. We tried lrtk on several different high-performance clusters but could not reproduce the same errors. So I think this error may be associated with the lack of commonly used C++ libraries to process sequencing data. 
Our suggestions are:
1. you can run the EMA alone and check the missing libraries. 
The precompiled EMA is located at (/home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/EMA/ema)
2. you may recompile the EMA program from the source code. The source codes could be found at (/home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/EMA/)
3. As we make modifications from EMA, a public third-party software. Installing the original EMA program may be helpful in solving this problem.

Similar strategies (suggestions 1 and 2), could be used for the fragment_construction program.
In addition, could you please provide more detailed information about the errors, such as the size of the alignment file and the reports running EMA and fragment_construction alone?


The second error about reformat.py was induced by lacking the header directory in the lrtk package. We have added the header directory on GitHub (https://github.com/ericcombiolab/LRTK/tree/main/script/header) and will correct this bug in the new version. Currently, users need to download this folder and place them under the library path (for example: /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/).

**Comment by btm685** [comment]
Thank you for the very quick response.  I will work on investigating the
EMA failure as well as downloading the header directory.  Would it be
possible to enhance lrtk by checking and bailing out if it receives
non-zero return codes from critical 3rd party applications?  Or at least
warnings if they are considered non-critical?

**Comment by btm685** [comment]
There are no missing shared libraries from ema:

ldd /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/EMA/ema
        linux-vdso.so.1 (0x00007ffd80d5c000)
        libstdc++.so.6 => /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/EMA/../../../../libstdc++.so.6 (0x00007f62391b8000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f62391af000)
        libz.so.1 => /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/EMA/../../../../libz.so.1 (0x00007f6239195000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f62390ae000)
        libgomp.so.1 => /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/EMA/../../../../libgomp.so.1 (0x00007f6239075000)
        libgcc_s.so.1 => /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/EMA/../../../../libgcc_s.so.1 (0x00007f623905a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6238e32000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f623936e000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6238e2d000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6238e28000)

also, it runs fine with no args:
/home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/EMA/ema
EMA version 0.6.2
note: use '/home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/EMA/ema help' for usage information.

with args, it reports an error msg that may be helpful:
/home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/EMA/ema align  -1 /home/bmatthews/lrtk-work/./WGS//Example_10x/FQ/Example_10x.Clean.R1.fq.sort.wb.fq -2 /home/bmatthews/lrtk-work/./WGS//Example_10x/FQ/Example_10x.Clean.R2.fq.sort.wb.fq -r ./database/GRCH38/genome.fa -R @RG\tID:Example\tSM:Example -p  10x  -t 32 | samtools view  -Sb  -  -o /home/bmatthews/lrtk-work/./WGS//Example_10x/BAM/tmp.ema.bam
error: malformed read group: '@RGtID:ExampletSM:Example'
(myenv) bmatthews@9eb281a1a2ad:~/lrtk-work$ echo $?
0

strangely enough, it has a return code of 0

**Comment by btm685** [comment]
after building EMA from source as well as downloading header files, re-ran function 7.  ema and construct_fragment were able to execute without error msgs or core files.  Reformat.py also had no problem finding the appropriate header, but it did fail looking for vcf-sort:

python /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/Reformat.py -r ./database/GRCH38/genome.fa -i /home/bmatthews/lrtk-work/./WGS//Example_10x/SV/tmp.vcf -o /home/bmatthews/lrtk-work/./WGS//Example_10x/SV/Example_10x.largevariants.vcf --add_header 38 --base_norm --gz_tbi^M
Vcf reformat start^M
/bin/sh: 1: vcf-sort: not found^M
^M
^M
^M
Vcf reformat finished^M
Time used: 23.59341049194336^M
Traceback (most recent call last):^M
  File "/home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script//vcf2json.py", line 107, in <module>^M
    main(sys.argv[1:])^M
  File "/home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script//vcf2json.py", line 37, in main^M
    lenref = len(LineArray[3])^M
IndexError: list index out of range^M
[2022-09-10 12:29:52.583816] report starts: python /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script//report.py -f /home/bmatthews/lrtk-work/./WGS//Example_10x/FQ/FASTQ.QC.json -b /home/bmatthews/lrtk-work/./WGS//Example_10x/QC/Fragment.json -m /home/bmatthews/lrtk-work/./WGS//Example_10x/QC/VCF.json -o /home/bmatthews/lrtk-work/./WGS//Example_10x/Report/Example_10x.report.html^M
[2022-09-10 12:29:52.704974] report fails: python /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script//report.py -f /home/bmatthews/lrtk-work/./WGS//Example_10x/FQ/FASTQ.QC.json -b /home/bmatthews/lrtk-work/./WGS//Example_10x/QC/Fragment.json -m /home/bmatthews/lrtk-work/./WGS//Example_10x/QC/VCF.json -o /home/bmatthews/lrtk-work/./WGS//Example_10x/Report/Example_10x.report.html^M
$ ^M
[typescript2.txt](https://github.com/ericcombiolab/LRTK/files/9540437/typescript2.txt)


see attached typescript2.txt for more details of the full run

**Comment by CicyYeung** [comment]
This error was induced by the uncompleted dependency. LRTK aims to provide
a standard and compatible VCF format for further data mining. The VCF files
are sorted by vcf-sort, compressed by bgzip and indexed by tabix. The
vcf-sort is a part of the VCFtools and can be installed by using “conda
install -c bioconda vcftools”. Both bgzip and tabix are part of the tabix
package, and could be installed by using the following commands: “conda
install -c bioconda tabix”. we will include the dependency in the next
version. Thanks!

**Comment by CicyYeung** [comment]
This error was induced by the uncompleted dependency. LRTK aims to provide a standard and compatible VCF format for further data mining. The VCF files are sorted by vcf-sort, compressed by bgzip and indexed by tabix. The vcf-sort is a part of the VCFtools and can be installed by using “conda install -c bioconda vcftools”. Both bgzip and tabix are part of the tabix package, and could be installed by using the following commands: “conda install -c bioconda tabix”. we will include the dependency in the next version. Thanks!

**Comment by btm685** [comment]
Thanks, I was able to get vcftools and tabix installed while near the end of another test run, and Reformat.py looks to have gotten past any error associated with not finding those dependencies.  Unfortunately, it did fail again, but with a bunch of errors like this:

python /home/bmatthews/.conda/envs/myenv/lib/python3.10/site-packages/script/Reformat.py -r ./database/GRCH38/genome.fa -i /home/bmatthews/lrtk-work/./WGS//Example_10x/SV/tmp.vcf -o /home/bmatthews/lrtk-work/./WGS//Example_10x/SV/Example_10x.largevariants.vcf --add_header 38 --base_norm --gz_tbi^M
Vcf reformat start^M
sort -k1,1d -k2,2n^M
^M
^M
[E::get_intv] Failed to parse TBX_VCF, was wrong -p [type] used?^M
The offending line was: ""^M
[E::get_intv] Failed to parse TBX_VCF, was wrong -p [type] used?^M
The offending line was: ""^M
[E::get_intv] Failed to parse TBX_VCF, was wrong -p [type] used?^M
The offending line was: ""^M

(and on and on for many hundreds of lines).   See attached file for the full run.


[typescript3.txt](https://github.com/ericcombiolab/LRTK/files/9541878/typescript3.txt)

Thanks,
Brent

**Comment by CicyYeung** [comment]
This may be a problem associated with the tabix package. As discussed in biostars (https://www.biostars.org/p/9530170/#9533081),  you would better attach the actual VCF file for me to check.

**Comment by btm685** [comment]
The input vcf file /home/bmatthews/lrtk-work/./WGS//Example_10x/SV/tmp.vcf is 0 bytes, so no wonder Reformat.py is not very happy.  It looks to be built out of cat-ting a bunch of (empty) Aquila_final_sorted.vcf files.  I assume these were probably created from all of the aquila_step1/step2/clean runs for each chromosome.

**Comment by CicyYeung** [comment]
As the SV module is LRTK is designed for completed whole genome sequencing data. It is very difficult to call SVs with the testing data. In our example results, the number of SVs is also 0.

**Comment by btm685** [comment]
Thanks Cicy for all your help, closing this issue.
